#!/bin/bash

#Force Windowed mode
mode=`gsettings get com.canonical.Unity8 usage-mode | sed -e "s/'//g"`
if [ "$mode" = "Staged" ]; then
  gsettings set com.canonical.Unity8 usage-mode Windowed
else
  gsettings set com.canonical.Unity8 usage-mode Windowed
  #Staged
fi

#Launch OpenHAB and HABPanel
browser="morph-browser"
terminal="com.ubuntu.terminal_terminal_0.9.0"
openhab="/usr/bin/openhab-cli start"

#Launch browser anyway
sleep 20 && ubuntu-app-launch $browser &

#Check local/remote shell
if [ -n "$SSH_TTY" ]; then
  #Launch Terminal (will trigger server start)
  ubuntu-app-launch $terminal
else
  #Start OpenHAB as we are in Terminal
  libertine-container-manager exec -c "$openhab"
fi

